name: "publish"
on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  
  upload-apk:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: apks
          path: ./release
      - name: Release
        uses: AButler/upload-release-assets@v3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-id: ${{needs.build.outputs.release_id}}
          files: "./release/**/*.apk"