name: "test-build"
on: [pull_request, push]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    environment: updater
    steps:
    - uses: "./.github/workflows/build.yml"
      with:
        platform: ${{ matrix.platform }}
    - uses: tauri-apps/tauri-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_PRIVATE_KEY: ${{secrets.TAURI_PRIVATE_KEY}}
        TAURI_KEY_PASSWORD: ${{secrets.TAURI_KEY_PASSWORD}}
      with:
        includeUpdaterJson: true


